/* Generated By:JavaCC: Do not edit this line. ParserSQLConstants.java */
package apprendreSQL.Model.analysisType.syntax;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserSQLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 9;
  /** RegularExpression Id. */
  int ABORT = 10;
  /** RegularExpression Id. */
  int ACTION = 11;
  /** RegularExpression Id. */
  int ADD = 12;
  /** RegularExpression Id. */
  int AFTER = 13;
  /** RegularExpression Id. */
  int ALL = 14;
  /** RegularExpression Id. */
  int ALTER = 15;
  /** RegularExpression Id. */
  int ANALYZE = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int AS = 18;
  /** RegularExpression Id. */
  int ASC = 19;
  /** RegularExpression Id. */
  int OLD = 20;
  /** RegularExpression Id. */
  int ATTACH = 21;
  /** RegularExpression Id. */
  int AUTOINCREMENT = 22;
  /** RegularExpression Id. */
  int BEFORE = 23;
  /** RegularExpression Id. */
  int BEGIN = 24;
  /** RegularExpression Id. */
  int BETWEEN = 25;
  /** RegularExpression Id. */
  int BY = 26;
  /** RegularExpression Id. */
  int CASCADE = 27;
  /** RegularExpression Id. */
  int CASE = 28;
  /** RegularExpression Id. */
  int CAST = 29;
  /** RegularExpression Id. */
  int CHECK = 30;
  /** RegularExpression Id. */
  int COLLATE = 31;
  /** RegularExpression Id. */
  int COLUMN = 32;
  /** RegularExpression Id. */
  int COMMIT = 33;
  /** RegularExpression Id. */
  int CONFLICT = 34;
  /** RegularExpression Id. */
  int CONSTRAINT = 35;
  /** RegularExpression Id. */
  int CREATE = 36;
  /** RegularExpression Id. */
  int CROSS = 37;
  /** RegularExpression Id. */
  int CURRENT_DATE = 38;
  /** RegularExpression Id. */
  int CURRENT_TIME = 39;
  /** RegularExpression Id. */
  int CURRENT_TIMESTAMP = 40;
  /** RegularExpression Id. */
  int DATABASE = 41;
  /** RegularExpression Id. */
  int DEFAULT_ = 42;
  /** RegularExpression Id. */
  int DEFERRABLE = 43;
  /** RegularExpression Id. */
  int DEFERRED = 44;
  /** RegularExpression Id. */
  int DELETE = 45;
  /** RegularExpression Id. */
  int DESC = 46;
  /** RegularExpression Id. */
  int DETACH = 47;
  /** RegularExpression Id. */
  int DISTINCT = 48;
  /** RegularExpression Id. */
  int DROP = 49;
  /** RegularExpression Id. */
  int EACH = 50;
  /** RegularExpression Id. */
  int ELSE = 51;
  /** RegularExpression Id. */
  int END = 52;
  /** RegularExpression Id. */
  int ESCAPE = 53;
  /** RegularExpression Id. */
  int EXCEPT = 54;
  /** RegularExpression Id. */
  int EXCLUSIVE = 55;
  /** RegularExpression Id. */
  int EXISTS = 56;
  /** RegularExpression Id. */
  int EXPLAIN = 57;
  /** RegularExpression Id. */
  int FAIL = 58;
  /** RegularExpression Id. */
  int FOR = 59;
  /** RegularExpression Id. */
  int FOREIGN = 60;
  /** RegularExpression Id. */
  int FROM = 61;
  /** RegularExpression Id. */
  int FULL = 62;
  /** RegularExpression Id. */
  int GLOB = 63;
  /** RegularExpression Id. */
  int GROUP = 64;
  /** RegularExpression Id. */
  int HAVING = 65;
  /** RegularExpression Id. */
  int IF = 66;
  /** RegularExpression Id. */
  int IGNORE = 67;
  /** RegularExpression Id. */
  int IMMEDIATE = 68;
  /** RegularExpression Id. */
  int IN = 69;
  /** RegularExpression Id. */
  int INDEX = 70;
  /** RegularExpression Id. */
  int INDEXED = 71;
  /** RegularExpression Id. */
  int INITIALLY = 72;
  /** RegularExpression Id. */
  int INNER = 73;
  /** RegularExpression Id. */
  int INSERT = 74;
  /** RegularExpression Id. */
  int INSTEAD = 75;
  /** RegularExpression Id. */
  int INTERSECT = 76;
  /** RegularExpression Id. */
  int INTO = 77;
  /** RegularExpression Id. */
  int IS = 78;
  /** RegularExpression Id. */
  int ISNULL = 79;
  /** RegularExpression Id. */
  int JOIN = 80;
  /** RegularExpression Id. */
  int KEY = 81;
  /** RegularExpression Id. */
  int LEFT = 82;
  /** RegularExpression Id. */
  int LIKE = 83;
  /** RegularExpression Id. */
  int LIMIT = 84;
  /** RegularExpression Id. */
  int MATCH = 85;
  /** RegularExpression Id. */
  int NATURAL = 86;
  /** RegularExpression Id. */
  int NO = 87;
  /** RegularExpression Id. */
  int NOT = 88;
  /** RegularExpression Id. */
  int NOTNULL = 89;
  /** RegularExpression Id. */
  int NULL = 90;
  /** RegularExpression Id. */
  int OF = 91;
  /** RegularExpression Id. */
  int OFFSET = 92;
  /** RegularExpression Id. */
  int ON = 93;
  /** RegularExpression Id. */
  int OR = 94;
  /** RegularExpression Id. */
  int ORDER = 95;
  /** RegularExpression Id. */
  int OUTER = 96;
  /** RegularExpression Id. */
  int PLAN = 97;
  /** RegularExpression Id. */
  int PRAGMA = 98;
  /** RegularExpression Id. */
  int PRIMARY = 99;
  /** RegularExpression Id. */
  int QUERY = 100;
  /** RegularExpression Id. */
  int RAISE = 101;
  /** RegularExpression Id. */
  int REFERENCES = 102;
  /** RegularExpression Id. */
  int REGEXP = 103;
  /** RegularExpression Id. */
  int REINDEX = 104;
  /** RegularExpression Id. */
  int RELEASE = 105;
  /** RegularExpression Id. */
  int RENAME = 106;
  /** RegularExpression Id. */
  int REPLACE = 107;
  /** RegularExpression Id. */
  int RESTRICT = 108;
  /** RegularExpression Id. */
  int RIGHT = 109;
  /** RegularExpression Id. */
  int ROLLBACK = 110;
  /** RegularExpression Id. */
  int ROW = 111;
  /** RegularExpression Id. */
  int SAVEPOINT = 112;
  /** RegularExpression Id. */
  int SELECT = 113;
  /** RegularExpression Id. */
  int SET = 114;
  /** RegularExpression Id. */
  int TABLE = 115;
  /** RegularExpression Id. */
  int TEMP = 116;
  /** RegularExpression Id. */
  int TEMPORARY = 117;
  /** RegularExpression Id. */
  int THEN = 118;
  /** RegularExpression Id. */
  int TO = 119;
  /** RegularExpression Id. */
  int TRANSACTION = 120;
  /** RegularExpression Id. */
  int TRIGGER = 121;
  /** RegularExpression Id. */
  int UNION = 122;
  /** RegularExpression Id. */
  int UNIQUE = 123;
  /** RegularExpression Id. */
  int UPDATE = 124;
  /** RegularExpression Id. */
  int USING = 125;
  /** RegularExpression Id. */
  int VACUUM = 126;
  /** RegularExpression Id. */
  int VALUES = 127;
  /** RegularExpression Id. */
  int VIEW = 128;
  /** RegularExpression Id. */
  int VIRTUAL = 129;
  /** RegularExpression Id. */
  int WHEN = 130;
  /** RegularExpression Id. */
  int WHERE = 131;
  /** RegularExpression Id. */
  int CONCATENATION = 132;
  /** RegularExpression Id. */
  int STAR = 133;
  /** RegularExpression Id. */
  int SLASH = 134;
  /** RegularExpression Id. */
  int MODULO = 135;
  /** RegularExpression Id. */
  int PLUS = 136;
  /** RegularExpression Id. */
  int MINUS = 137;
  /** RegularExpression Id. */
  int SHIFT_HIGH = 138;
  /** RegularExpression Id. */
  int SHIFT_LOW = 139;
  /** RegularExpression Id. */
  int BIT_AND = 140;
  /** RegularExpression Id. */
  int BIT_OR = 141;
  /** RegularExpression Id. */
  int BIT_NOT = 142;
  /** RegularExpression Id. */
  int LESS = 143;
  /** RegularExpression Id. */
  int LESS_OR_EQUAL = 144;
  /** RegularExpression Id. */
  int GREATER = 145;
  /** RegularExpression Id. */
  int GREATER_OR_EQUAL = 146;
  /** RegularExpression Id. */
  int EQUAL_1 = 147;
  /** RegularExpression Id. */
  int EQUAL_2 = 148;
  /** RegularExpression Id. */
  int NOT_EQUAL_1 = 149;
  /** RegularExpression Id. */
  int NOT_EQUAL_2 = 150;
  /** RegularExpression Id. */
  int NUMERIC = 151;
  /** RegularExpression Id. */
  int EXPONENT = 152;
  /** RegularExpression Id. */
  int STRING = 153;
  /** RegularExpression Id. */
  int BLOB = 154;
  /** RegularExpression Id. */
  int PARAMETER = 155;
  /** RegularExpression Id. */
  int ID = 156;
  /** RegularExpression Id. */
  int LP = 157;
  /** RegularExpression Id. */
  int RP = 158;
  /** RegularExpression Id. */
  int SEMICOLON = 159;
  /** RegularExpression Id. */
  int COMMA = 160;
  /** RegularExpression Id. */
  int DOT = 161;
  /** RegularExpression Id. */
  int DIGIT = 162;
  /** RegularExpression Id. */
  int CHAR = 163;
  /** RegularExpression Id. */
  int HEX_CHAR = 164;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_BLOCK_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"\\r\"",
    "<LINE_COMMENT>",
    "\"/*\"",
    "<token of kind 8>",
    "\"*/\"",
    "\"ABORT\"",
    "\"ACTION\"",
    "\"ADD\"",
    "\"AFTER\"",
    "\"ALL\"",
    "\"ALTER\"",
    "\"ANALYZE\"",
    "\"AND\"",
    "\"AS\"",
    "\"ASC\"",
    "\"old\"",
    "\"ATTACH\"",
    "\"AUTOINCREMENT\"",
    "\"BEFORE\"",
    "\"BEGIN\"",
    "\"BETWEEN\"",
    "\"BY\"",
    "\"CASCADE\"",
    "\"CASE\"",
    "\"CAST\"",
    "\"CHECK\"",
    "\"COLLATE\"",
    "\"COLUMN\"",
    "\"COMMIT\"",
    "\"CONFLICT\"",
    "\"CONSTRAINT\"",
    "\"CREATE\"",
    "\"CROSS\"",
    "\"CURRENT_DATE\"",
    "\"CURRENT_TIME\"",
    "\"CURRENT_TIMESTAMP\"",
    "\"DATABASE\"",
    "\"DEFAULT\"",
    "\"DEFERRABLE\"",
    "\"DEFERRED\"",
    "\"DELETE\"",
    "\"DESC\"",
    "\"DETACH\"",
    "\"DISTINCT\"",
    "\"DROP\"",
    "\"EACH\"",
    "\"ELSE\"",
    "\"END\"",
    "\"ESCAPE\"",
    "\"EXCEPT\"",
    "\"EXCLUSIVE\"",
    "\"EXISTS\"",
    "\"EXPLAIN\"",
    "\"FAIL\"",
    "\"FOR\"",
    "\"FOREIGN\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"GLOB\"",
    "\"GROUP\"",
    "\"HAVING\"",
    "\"IF\"",
    "\"IGNORE\"",
    "\"IMMEDIATE\"",
    "\"IN\"",
    "\"INDEX\"",
    "\"INDEXED\"",
    "\"INITIALLY\"",
    "\"INNER\"",
    "\"INSERT\"",
    "\"INSTEAD\"",
    "\"INTERSECT\"",
    "\"INTO\"",
    "\"IS\"",
    "\"ISNULL\"",
    "\"JOIN\"",
    "\"KEY\"",
    "\"LEFT\"",
    "\"LIKE\"",
    "\"LIMIT\"",
    "\"MATCH\"",
    "\"NATURAL\"",
    "\"NO\"",
    "\"NOT\"",
    "\"NOTNULL\"",
    "\"NULL\"",
    "\"OF\"",
    "\"OFFSET\"",
    "\"ON\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"OUTER\"",
    "\"PLAN\"",
    "\"PRAGMA\"",
    "\"PRIMARY\"",
    "\"QUERY\"",
    "\"RAISE\"",
    "\"REFERENCES\"",
    "\"REGEXP\"",
    "\"REINDEX\"",
    "\"RELEASE\"",
    "\"RENAME\"",
    "\"REPLACE\"",
    "\"RESTRICT\"",
    "\"RIGHT\"",
    "\"ROLLBACK\"",
    "\"ROW\"",
    "\"SAVEPOINT\"",
    "\"SELECT\"",
    "\"SET\"",
    "\"TABLE\"",
    "\"TEMP\"",
    "\"TEMPORARY\"",
    "\"THEN\"",
    "\"TO\"",
    "\"TRANSACTION\"",
    "\"TRIGGER\"",
    "\"UNION\"",
    "\"UNIQUE\"",
    "\"UPDATE\"",
    "\"USING\"",
    "\"VACUUM\"",
    "\"VALUES\"",
    "\"VIEW\"",
    "\"VIRTUAL\"",
    "\"WHEN\"",
    "\"WHERE\"",
    "\"||\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"+\"",
    "\"-\"",
    "\"<<\"",
    "\">>\"",
    "\"&\"",
    "\"|\"",
    "\"~\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<>\"",
    "<NUMERIC>",
    "<EXPONENT>",
    "<STRING>",
    "<BLOB>",
    "<PARAMETER>",
    "<ID>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "<DIGIT>",
    "<CHAR>",
    "<HEX_CHAR>",
  };

}
